#!/bin/bash -e

mkdir -p config/includes.chroot/usr/src

for x in sugar{-datastore,-artwork,-toolkit,-toolkit-gtk3,}; do
    P=config/includes.chroot/usr/src/$x
    if [ ! -e $P ]; then
	git clone https://github.com/sugarlabs/$x $P
    fi
done

mkdir -p config/includes.chroot/usr/src/sugar-activities

function clone {
    P=config/includes.chroot/usr/src/sugar-activities/$2
    if [ ! -e $P ]; then
	git clone $1 $P
    fi
}

clone https://github.com/sugarlabs/browse-activity.git     Browse.activity
clone https://github.com/sugarlabs/sugarlabs-calculate.git Calculate.activity
clone https://github.com/sugarlabs/chat.git                Chat.activity
clone https://github.com/sugarlabs/imageviewer-activity    ImageViewer.activity
clone https://github.com/sugarlabs/jukebox-activity.git    Jukebox.activity
clone https://github.com/sugarlabs/log-activity            Log.activity
clone https://github.com/sugarlabs/Pippy                   Pippy.activity
clone https://github.com/sugarlabs/read-activity           Read.activity
clone https://github.com/sugarlabs/terminal-activity       Terminal.activity
clone https://github.com/sugarlabs/turtleart-activity.git  TurtleBlocks.activity
clone https://github.com/sugarlabs/write-activity          Write.activity

[ ! -e /usr/bin/lb ] && sudo apt install -y live-build

sudo lb build
