#!/bin/bash -e
# Written by James Cameron <quozl@laptop.org>
# Public Domain

# install live-build if not present
[ ! -e /usr/bin/lb ] && apt install -y live-build

# destroy previous configuration
rm -rvf config chroot

# clean build system
lb clean --all

# begin configuration
lb config

# begin build
lb build

# report success
echo normal successful completion
