#!/bin/bash

# install git if not present
[ ! -e /usr/bin/git ] && apt install -y git

# make place to put sources
C=cache.sugar/usr/src
mkdir -p $C

# clone the sugar modules
for x in sugar{-datastore,-artwork,-toolkit-gtk3,} gwebsockets; do
    P=$C/$x
    if [ ! -e $P ]; then
	git clone --depth 2 https://github.com/sugarlabs/$x $P
    fi
done

# prepare for activities
mkdir -p $C/sugar-activities

function clone {
    P=$C/sugar-activities/$2
    if [ ! -e $P ]; then
	git clone --depth 2 $1 $P
    fi
}

# clone demonstration activities, the fructose set
clone https://github.com/sugarlabs/browse-activity      Browse.activity
clone https://github.com/sugarlabs/sugarlabs-calculate  Calculate.activity
clone https://github.com/sugarlabs/chat                 Chat.activity
clone https://github.com/sugarlabs/imageviewer-activity ImageViewer.activity
clone https://github.com/sugarlabs/jukebox-activity     Jukebox.activity
clone https://github.com/sugarlabs/log-activity         Log.activity
clone https://github.com/sugarlabs/Pippy                Pippy.activity
clone https://github.com/sugarlabs/read-activity        Read.activity
clone https://github.com/sugarlabs/terminal-activity    Terminal.activity
clone https://github.com/sugarlabs/turtleart-activity   TurtleBlocks.activity
clone https://github.com/sugarlabs/write-activity       Write.activity

# clone assorted other activities, the honey set
clone https://github.com/sugarlabs/memorize-activity Memorize.activity

# clone custom activities
#clone https://github.com/my/repository.git My.activity

# live build configuration step
lb config noauto \
   --distribution buster \
   --debian-installer live
	"${@}"

# customise configuration with files held in sugar-live-build git repository
cp -rv src/config .

# add sugar and activity source code to the build as hardlinks
mkdir -p config/includes.chroot/usr/src
cp -rlv $C/* config/includes.chroot/usr/src/
